# Generated by Django 5.1.6 on 2025-02-22 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_game_team1_score_game_team2_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_teams',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='number_of_teams',
            field=models.IntegerField(default=0),
        ),
    ]
