# Generated by Django 5.1.6 on 2025-02-23 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_game_field_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='coin_toss_winner_is_team1',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='game',
            name='offense_is_team1',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='ScoreEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('TD', 'Touchdown'), ('PAT1', '1-Point-Try'), ('PAT2', '2-Point-Try'), ('SAFETY', 'Safety')], max_length=10)),
                ('trikot', models.IntegerField(blank=True, null=True)),
                ('points_awarded', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_events', to='events.game')),
            ],
        ),
    ]
